services:
  remuxHTTP:
    image: ghcr.io/robertaidenschofield/remuxhttp:nightly
    container_name: remuxHTTP
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - ./data:/data
    environment:
      - PORT=3000
      - DATA_DIR=/data

